window.charData = {
  clans: [
    {
      id: 'hyuga',
      name: 'Clan Hyūga',
      emoji: '👁️',
      rank: 'Byakugan Elite',
      summary: { HP:'Muy Alto', MP:'Medio', ATK:'Medio', DEF:'Alto', Vel:'Medio', CRT:'Bajo' },
      modifiers: { hp: 1.08, mp: 0.9, atk: 0.98, def: 1.12 },
      members: ['Neji Hyūga', 'Hinata Hyūga', 'Hiashi Hyūga', 'Hanabi Hyūga'],
      memberEmoji: ['🥋', '🌸', '🧘', '🌺'],
    },
    {
      id: 'uchiha',
      name: 'Clan Uchiha',
      emoji: '🔥',
      rank: 'Sharingan Prodigy',
      summary: { HP:'Medio', MP:'Muy Alto', ATK:'Muy Alto', DEF:'Bajo', Vel:'Alto', CRT:'Muy Alto' },
      modifiers: { hp: 0.95, mp: 1.08, atk: 1.16, def: 0.92 },
      members: ['Madara Uchiha', 'Itachi Uchiha', 'Sasuke Uchiha', 'Obito Uchiha'],
      memberEmoji: ['💀', '🌙', '⚡', '🌀'],
    },
    {
      id: 'senju',
      name: 'Clan Senju',
      emoji: '🌿',
      rank: 'Will of Fire',
      summary: { HP:'Muy Alto', MP:'Muy Alto', ATK:'Alto', DEF:'Alto', Vel:'Medio', CRT:'Medio' },
      modifiers: { hp: 1.12, mp: 1.12, atk: 1.04, def: 1.05 },
      members: ['Hashirama Senju', 'Tobirama Senju', 'Tsunade Senju', 'Itama Senju'],
      memberEmoji: ['🌳', '💧', '👊', '🍃'],
    },
    {
      id: 'uzumaki',
      name: 'Clan Uzumaki',
      emoji: '🌀',
      rank: 'Chakra Titan',
      summary: { HP:'Muy Alto', MP:'Muy Alto', ATK:'Medio', DEF:'Medio', Vel:'Bajo', CRT:'Bajo' },
      modifiers: { hp: 1.1, mp: 1.16, atk: 0.96, def: 1 },
      members: ['Kushina Uzumaki', 'Naruto Uzumaki', 'Nagato Uzumaki', 'Karin Uzumaki'],
      memberEmoji: ['🦊', '🍜', '🌧️', '💊'],
    },
    {
      id: 'nara',
      name: 'Clan Nara',
      emoji: '🦌',
      rank: 'Shadow Tactician',
      summary: { HP:'Bajo', MP:'Medio', ATK:'Bajo', DEF:'Bajo', Vel:'Bajo', CRT:'Muy Alto' },
      modifiers: { hp: 0.9, mp: 1, atk: 0.92, def: 0.9 },
      members: ['Shikamaru Nara', 'Shikaku Nara', 'Shikadai Nara', 'Ensui Nara'],
      memberEmoji: ['🌑', '🧠', '💨', '🌫️'],
    },
    {
      id: 'otsutsuki',
      name: 'Clan Ōtsutsuki',
      emoji: '🌕',
      rank: 'Divine Vessel',
      summary: { HP:'Muy Alto', MP:'Muy Alto', ATK:'Muy Alto', DEF:'Alto', Vel:'Alto', CRT:'Alto' },
      modifiers: { hp: 1.06, mp: 1.18, atk: 1.12, def: 1.06 },
      members: ['Kaguya Ōtsutsuki', 'Hagoromo Ōtsutsuki', 'Hamura Ōtsutsuki', 'Toneri Ōtsutsuki'],
      memberEmoji: ['👁️', '☯️', '🌙', '🌑'],
    },
  ],
};
