window.gameData = {
  clans: [
    {
      id: 'hyuga',
      name: 'CLAN HYŪGA',
      emoji: '👁️',
      summary: { HP: 'Muy Alto', MP: 'Medio', ATK: 'Medio', DEF: 'Alto', VEL: 'Medio', CTR: 'Bajo', CDMG: 'Medio', EVA: 'Medio', RES: 'Muy Alto', REGEN: 'Bajo' },
      members: ['Neji Hyūga', 'Hinata Hyūga', 'Hiashi Hyūga', 'Hanabi Hyūga'],
      memberEmoji: ['🥋', '🌸', '🧘', '🌺'],
      stats: { hpMax: 120, mpMax: 80, atk: 15, def: 14, vel: 10, ctr: 2, cdmg: 110, eva: 5, res: 10, regen: 1 },
    },
    {
      id: 'uchiha',
      name: 'CLAN UCHIHA',
      emoji: '🔥',
      summary: { HP: 'Medio', MP: 'Muy Alto', ATK: 'Muy Alto', DEF: 'Bajo', VEL: 'Alto', CTR: 'Muy Alto', CDMG: 'Muy Alto', EVA: 'Alto', RES: 'Medio', REGEN: 'Bajo' },
      members: ['Madara Uchiha', 'Itachi Uchiha', 'Sasuke Uchiha', 'Obito Uchiha'],
      memberEmoji: ['💀', '🌙', '⚡', '🌀'],
      stats: { hpMax: 100, mpMax: 100, atk: 18, def: 10, vel: 12, ctr: 8, cdmg: 115, eva: 6, res: 8, regen: 2 },
    },
    {
      id: 'senju',
      name: 'CLAN SENJU',
      emoji: '🌿',
      summary: { HP: 'Muy Alto', MP: 'Muy Alto', ATK: 'Alto', DEF: 'Alto', VEL: 'Medio', CTR: 'Medio', CDMG: 'Medio', EVA: 'Bajo', RES: 'Muy Alto', REGEN: 'Muy Alto' },
      members: ['Hashirama Senju', 'Tobirama Senju', 'Tsunade Senju', 'Itama Senju'],
      memberEmoji: ['🌳', '💧', '👊', '🍃'],
      stats: { hpMax: 130, mpMax: 110, atk: 16, def: 12, vel: 11, ctr: 5, cdmg: 112, eva: 4, res: 12, regen: 4 },
    },
    {
      id: 'uzumaki',
      name: 'CLAN UZUMAKI',
      emoji: '🌀',
      summary: { HP: 'Muy Alto', MP: 'Muy Alto', ATK: 'Medio', DEF: 'Medio', VEL: 'Bajo', CTR: 'Bajo', CDMG: 'Medio', EVA: 'Bajo', RES: 'Muy Alto', REGEN: 'Muy Alto' },
      members: ['Kushina Uzumaki', 'Naruto Uzumaki', 'Nagato Uzumaki', 'Karin Uzumaki'],
      memberEmoji: ['🦊', '🍜', '🌧️', '💊'],
      stats: { hpMax: 125, mpMax: 115, atk: 14, def: 11, vel: 9, ctr: 4, cdmg: 111, eva: 3, res: 14, regen: 5 },
    },
    {
      id: 'nara',
      name: 'CLAN NARA',
      emoji: '🦌',
      summary: { HP: 'Bajo', MP: 'Medio', ATK: 'Bajo', DEF: 'Bajo', VEL: 'Bajo', CTR: 'Muy Alto', CDMG: 'Muy Alto', EVA: 'Bajo', RES: 'Muy Alto', REGEN: 'Bajo' },
      members: ['Shikamaru Nara', 'Shikaku Nara', 'Shikadai Nara', 'Ensui Nara'],
      memberEmoji: ['🌑', '🧠', '💨', '🌫️'],
      stats: { hpMax: 95, mpMax: 90, atk: 13, def: 9, vel: 8, ctr: 10, cdmg: 118, eva: 4, res: 16, regen: 2 },
    },
    {
      id: 'otsutsuki',
      name: 'CLAN ŌTSUTSUKI',
      emoji: '🌕',
      summary: { HP: 'Muy Alto', MP: 'Muy Alto', ATK: 'Muy Alto', DEF: 'Alto', VEL: 'Alto', CTR: 'Alto', CDMG: 'Muy Alto', EVA: 'Medio', RES: 'Muy Alto', REGEN: 'Alto' },
      members: ['Kaguya Ōtsutsuki', 'Hagoromo Ōtsutsuki', 'Hamura Ōtsutsuki', 'Toneri Ōtsutsuki'],
      memberEmoji: ['👁️', '☯️', '🌙', '🌑'],
      stats: { hpMax: 115, mpMax: 120, atk: 17, def: 13, vel: 11, ctr: 7, cdmg: 114, eva: 5, res: 15, regen: 3 },
    },
  ],
  initialState: {
    hp: 720,
    hpMax: 1000,
    mp: 290,
    mpMax: 500,
    exp: 4400,
    expMax: 10000,
    gold: 4320,
    atk: 1240,
    def: 880,
    level: 23,
    activeSection: 'heroe',
    missionProg: 63,
  },
  profile: {
    clanId: 'uzumaki',
    clanName: 'CLAN UZUMAKI',
    heroName: 'Naruto Uzumaki',
    heroEmoji: '🍜',
  },
  sections: {
    heroe:        { icon:'🥷', title:'HÉROE',            desc:'Consulta y mejora el equipo de tu shinobi. Cambia armadura, armas y accesorios para maximizar tu poder de combate.' },
    misiones:     { icon:'📜', title:'MISIONES',         desc:'Tienes 3 misiones pendientes. Completa misiones diarias, de historia y especiales para ganar EXP y recursos.' },
    clanes:       { icon:'⛩️', title:'CLANES',           desc:'Únete o crea tu clan. Participa en guerras de clanes y desbloquea jutsus exclusivos de linaje.' },
    eventos:      { icon:'🎴', title:'EVENTOS',          desc:'¡Evento especial activo! Festival del Chakra Lunar: consigue multiplicadores ×3 de EXP durante 2 horas.' },
    jutsus:       { icon:'🌀', title:'JUTSUS',           desc:'Gestiona tus técnicas ninja. Equipa hasta 4 jutsus activos y mejora sus rangos con sellos de chakra.' },
    batallas:     { icon:'⚔️', title:'BATALLAS',         desc:'Modo PvP y arena de rango. Desafía a otros jugadores y sube en la tabla clasificatoria mundial.' },
    invocaciones: { icon:'✨', title:'INVOCACIONES',     desc:'Invoca nuevos compañeros y objetos míticos. Utiliza pergaminos de convocación para obtener aliados S-Rank.' },
    habilidades:  { icon:'🌿', title:'ÁRBOL DE HABILIDAD', desc:'Asigna puntos de habilidad en ramas de Ninjutsu, Taijutsu y Genjutsu para personalizar tu estilo de combate.' },
    ajustes:      { icon:'⚙️', title:'AJUSTES',          desc:'Configura notificaciones, audio, gráficos y tu cuenta de shinobi. También puedes vincular tu aldea.' },
  },
  combatLines: [
    { actor:'Naruto', msg:'usa', jutsu:'Rasengan', dmg:'-342' },
    { actor:'Naruto', msg:'ataca a', jutsu:'Kabuto', dmg:'-128' },
    { actor:'Kabuto', msg:'contraataca', jutsu:'', dmg:'-89' },
    { actor:'Naruto', msg:'recupera chakra', jutsu:'', heal:'+50 MP' },
    { actor:'Naruto', msg:'usa', jutsu:'Kage Bunshin no Jutsu', dmg:'-210' },
    { actor:'Kabuto', msg:'usa', jutsu:'Chakra Escalpelo', dmg:'-155' },
    { actor:'Naruto', msg:'bloquea el ataque de', jutsu:'Kabuto', dmg:'-0' },
    { actor:'Naruto', msg:'obtiene', jutsu:'', heal:'+80 EXP' },
    { actor:'Naruto', msg:'usa', jutsu:'Tajuu Kage Bunshin', dmg:'-480' },
    { actor:'Kabuto', msg:'es derrotado!', jutsu:'', dmg:'' },
  ],
};
