window.gameData = {
  initialState: {
    hp: 720,
    hpMax: 1000,
    mp: 290,
    mpMax: 500,
    exp: 4400,
    expMax: 10000,
    gold: 4320,
    atk: 1240,
    def: 880,
    level: 23,
    activeSection: 'heroe',
    missionProg: 63,
  },
  clanPresets: [
    {
      id: 'hyuga',
      name: 'Clan Hyūga',
      emoji: '👁️',
      rank: 'Byakugan Elite',
      summary: { HP:'Muy Alto', MP:'Medio', ATK:'Medio', DEF:'Alto', VEL:'Medio', CTR:'Bajo', CDMG:'Medio', EVA:'Medio', RES:'Muy Alto', REGEN:'Bajo' },
      stateMult: { hpMax: 1.2, mpMax: 1.05, atk: 1.05, def: 1.2 },
      equipBase: { HP: 120, MP: 75, ATK: 11, DEF: 6.4, VEL: 10.6, CTR: 4.2, EVA: 3.4, RES: 4.6, REGEN: 0.9, ASPD: 1.0, CDMG: 158 },
    },
    {
      id: 'uchiha',
      name: 'Clan Uchiha',
      emoji: '🔥',
      rank: 'Sharingan Prodigio',
      summary: { HP:'Medio', MP:'Muy Alto', ATK:'Muy Alto', DEF:'Bajo', VEL:'Alto', CTR:'Muy Alto', CDMG:'Muy Alto', EVA:'Alto', RES:'Medio', REGEN:'Bajo' },
      stateMult: { hpMax: 1.0, mpMax: 1.25, atk: 1.28, def: 0.92 },
      equipBase: { HP: 100, MP: 65, ATK: 13, DEF: 4.6, VEL: 11.5, CTR: 7.4, EVA: 4.3, RES: 3.2, REGEN: 0.9, ASPD: 1.08, CDMG: 172 },
    },
    {
      id: 'senju',
      name: 'Clan Senju',
      emoji: '🌿',
      rank: 'Voluntad de Fuego',
      summary: { HP:'Muy Alto', MP:'Muy Alto', ATK:'Alto', DEF:'Alto', VEL:'Medio', CTR:'Medio', CDMG:'Medio', EVA:'Bajo', RES:'Muy Alto', REGEN:'Muy Alto' },
      stateMult: { hpMax: 1.28, mpMax: 1.18, atk: 1.12, def: 1.15 },
      equipBase: { HP: 130, MP: 72, ATK: 12, DEF: 6.2, VEL: 10.2, CTR: 5.2, EVA: 2.8, RES: 4.9, REGEN: 1.4, ASPD: 1.0, CDMG: 160 },
    },
    {
      id: 'uzumaki',
      name: 'Clan Uzumaki',
      emoji: '🌀',
      rank: 'Chakra Infinito',
      summary: { HP:'Muy Alto', MP:'Muy Alto', ATK:'Medio', DEF:'Medio', VEL:'Bajo', CTR:'Bajo', CDMG:'Medio', EVA:'Bajo', RES:'Muy Alto', REGEN:'Muy Alto' },
      stateMult: { hpMax: 1.25, mpMax: 1.22, atk: 1.0, def: 1.0 },
      equipBase: { HP: 125, MP: 78, ATK: 10, DEF: 5.2, VEL: 9.4, CTR: 4.0, EVA: 2.4, RES: 5.4, REGEN: 1.55, ASPD: 0.98, CDMG: 155 },
    },
    {
      id: 'nara',
      name: 'Clan Nara',
      emoji: '🦌',
      rank: 'Estratega de Sombras',
      summary: { HP:'Bajo', MP:'Medio', ATK:'Bajo', DEF:'Bajo', VEL:'Bajo', CTR:'Muy Alto', CDMG:'Muy Alto', EVA:'Bajo', RES:'Muy Alto', REGEN:'Bajo' },
      stateMult: { hpMax: 0.9, mpMax: 1.1, atk: 0.93, def: 0.92 },
      equipBase: { HP: 90, MP: 60, ATK: 9, DEF: 4.3, VEL: 9.0, CTR: 8.0, EVA: 2.2, RES: 5.6, REGEN: 0.85, ASPD: 0.96, CDMG: 178 },
    },
    {
      id: 'otsutsuki',
      name: 'Clan Ōtsutsuki',
      emoji: '🌕',
      rank: 'Linaje Divino',
      summary: { HP:'Muy Alto', MP:'Muy Alto', ATK:'Muy Alto', DEF:'Alto', VEL:'Alto', CTR:'Alto', CDMG:'Muy Alto', EVA:'Medio', RES:'Muy Alto', REGEN:'Alto' },
      stateMult: { hpMax: 1.18, mpMax: 1.3, atk: 1.22, def: 1.12 },
      equipBase: { HP: 118, MP: 82, ATK: 12.5, DEF: 5.8, VEL: 11.0, CTR: 6.5, EVA: 3.4, RES: 5.2, REGEN: 1.2, ASPD: 1.05, CDMG: 170 },
    },
  ],
  sections: {
    heroe:        { icon:'🥷', title:'HÉROE',            desc:'Consulta y mejora el equipo de tu shinobi. Cambia armadura, armas y accesorios para maximizar tu poder de combate.' },
    misiones:     { icon:'📜', title:'MISIONES',         desc:'Tienes 3 misiones pendientes. Completa misiones diarias, de historia y especiales para ganar EXP y recursos.' },
    clanes:       { icon:'⛩️', title:'CLANES',           desc:'Únete o crea tu clan. Participa en guerras de clanes y desbloquea jutsus exclusivos de linaje.' },
    eventos:      { icon:'🎴', title:'EVENTOS',          desc:'¡Evento especial activo! Festival del Chakra Lunar: consigue multiplicadores ×3 de EXP durante 2 horas.' },
    jutsus:       { icon:'🌀', title:'JUTSUS',           desc:'Gestiona tus técnicas ninja. Equipa hasta 4 jutsus activos y mejora sus rangos con sellos de chakra.' },
    batallas:     { icon:'⚔️', title:'BATALLAS',         desc:'Modo PvP y arena de rango. Desafía a otros jugadores y sube en la tabla clasificatoria mundial.' },
    invocaciones: { icon:'✨', title:'INVOCACIONES',     desc:'Invoca nuevos compañeros y objetos míticos. Utiliza pergaminos de convocación para obtener aliados S-Rank.' },
    habilidades:  { icon:'🌿', title:'ÁRBOL DE HABILIDAD', desc:'Asigna puntos de habilidad en ramas de Ninjutsu, Taijutsu y Genjutsu para personalizar tu estilo de combate.' },
    ajustes:      { icon:'⚙️', title:'AJUSTES',          desc:'Configura notificaciones, audio, gráficos y tu cuenta de shinobi. También puedes vincular tu aldea.' },
  },
  combatLines: [
    { actor:'Naruto', msg:'usa', jutsu:'Rasengan', dmg:'-342' },
    { actor:'Naruto', msg:'ataca a', jutsu:'Kabuto', dmg:'-128' },
    { actor:'Kabuto', msg:'contraataca', jutsu:'', dmg:'-89' },
    { actor:'Naruto', msg:'recupera chakra', jutsu:'', heal:'+50 MP' },
    { actor:'Naruto', msg:'usa', jutsu:'Kage Bunshin no Jutsu', dmg:'-210' },
    { actor:'Kabuto', msg:'usa', jutsu:'Chakra Escalpelo', dmg:'-155' },
    { actor:'Naruto', msg:'bloquea el ataque de', jutsu:'Kabuto', dmg:'-0' },
    { actor:'Naruto', msg:'obtiene', jutsu:'', heal:'+80 EXP' },
    { actor:'Naruto', msg:'usa', jutsu:'Tajuu Kage Bunshin', dmg:'-480' },
    { actor:'Kabuto', msg:'es derrotado!', jutsu:'', dmg:'' },
  ],
};
